In [1]:
# Dependencies
import pandas as pd
from pathlib import Path

In [4]:
# Load in file and store filepath in a variable
transit_file = Path("Resource/Metro-Systems-Worldwide.csv")

In [5]:
# Read and display the CSV with Pandas
transit_df = pd.read_csv(transit_file)
transit_df.head()

,City,Country\r\nregion,Name,Service\r\nopened,Last\r\nexpanded,Stations,System length,Annual ridership\r\n(millions)
0,Algiers,Algeria,Algiers Metro,2011,2018,19,18.5 km (11.5 mi),45.3 (2019)
1,Buenos Aires,Argentina,Buenos Aires Underground,1913,2019,78,56.7 km (35.2 mi),74.0 (2020)
2,Yerevan,Armenia,Yerevan Metro,1981,1996,10,12.1 km (7.5 mi),23.3 (2022)
3,Sydney,Australia,Sydney Metro,2019,–,13,36 km (22 mi),16.3 (2022)
4,Vienna,Austria,Vienna U-Bahn,1978,2017,98,83.3 km (51.8 mi),459.8 (2019)

In [6]:
# List all the columns in the table
transit_df.columns

Index(['City', 'Country\r\nregion', 'Name', 'Service\r\nopened',
       'Last\r\nexpanded', 'Stations', 'System length',
       'Annual ridership\r\n(millions)'],
      dtype='object')

In [8]:
# Use .rename(columns={}) to rename columns
transit_renamed_df = transit_df.rename(columns={"Country\r\nregion":"Country region", 
                                                "Service\r\nopened":"Service opened",
                                                "Last\r\nexpanded":"Last expanded",
                                                "Annual ridership\r\n(millions)":"Annual ridership (millions)"})
transit_renamed_df.head(20)

,City,Country region,Name,Service opened,Last expanded,Stations,System length,Annual ridership (millions)
0,Algiers,Algeria,Algiers Metro,2011,2018,19,18.5 km (11.5 mi),45.3 (2019)
1,Buenos Aires,Argentina,Buenos Aires Underground,1913,2019,78,56.7 km (35.2 mi),74.0 (2020)
2,Yerevan,Armenia,Yerevan Metro,1981,1996,10,12.1 km (7.5 mi),23.3 (2022)
3,Sydney,Australia,Sydney Metro,2019,–,13,36 km (22 mi),16.3 (2022)
4,Vienna,Austria,Vienna U-Bahn,1978,2017,98,83.3 km (51.8 mi),459.8 (2019)
5,Baku,Azerbaijan,Baku Metro,1967,2022,27,40.7 km (25.3 mi),202.5 (2022)
6,Dhaka,Bangladesh,Dhaka Metro Rail,2022,–,9,11.7 km (7.3 mi),NaN
7,Minsk,Belarus,Minsk Metro,1984,2020,33,40.8 km (25.4 mi),225.9 (2022)
8,Brussels,Belgium,Brussels Metro,1976,2009,59,39.9 km (24.8 mi),96.3 (2021)
9,Belo Horizonte,Brazil,Belo Horizonte Metro,1986,2002,19,28.1 km (17.5 mi),54.4 (2019)
10,Brasília,Brazil,Federal District Metro,2001,2020,27,42.38 km (26.33 mi),42.8 (2019)
11,Fortaleza,Brazil,Fortaleza Metro,2012,2013,20,24.1 km (15.0 mi),11.7 (2018)
12,Porto Alegre,Brazil,Porto Alegre Metro,1985,2014,22,43.8 km (27.2 mi),48.1 (2019)
13,Recife,Brazil,Recife Metro,1985,2009,28,39.5 km (24.5 mi),93.5 (2019)
14,Rio de Janeiro,Brazil,Rio de Janeiro Metro,1979,2016,41,58 km (36 mi),118.7 (2020)
15,Salvador,Brazil,Salvador Metro,2014,2018,19,32.5 km (20.2 mi),62 (2020)
16,São Paulo,Brazil,São Paulo Metro,1974,2021,89,104.4 km (64.9 mi),"1,104.149 (2022)"
17,Sofia,Bulgaria,Sofia Metro,1998,2021,44,52 km (32 mi),92.4 (2019)
18,Montreal,Canada,Montreal Metro,1966,2007,68,69.2 km (43.0 mi),245.5 (2022)
19,Toronto,Canada,Toronto Subway,1954,2017,75,76.9 km (47.8 mi),235.7 (2022)

In [9]:
transit_renamed_df.count()

City                           205
Country region                 205
Name                           205
Service opened                 205
Last expanded                  205
Stations                       205
System length                  205
Annual ridership (millions)    189
dtype: int64

In [10]:
drop_na_df = transit_renamed_df.dropna(how='any')

In [12]:
drop_na_df.count()

City                           189
Country region                 189
Name                           189
Service opened                 189
Last expanded                  189
Stations                       189
System length                  189
Annual ridership (millions)    189
dtype: int64

In [15]:
drop_na_df.head(10)

,City,Country region,Name,Service opened,Last expanded,Stations,System length,Annual ridership (millions)
0,Algiers,Algeria,Algiers Metro,2011,2018,19,18.5 km (11.5 mi),45.3 (2019)
1,Buenos Aires,Argentina,Buenos Aires Underground,1913,2019,78,56.7 km (35.2 mi),74.0 (2020)
2,Yerevan,Armenia,Yerevan Metro,1981,1996,10,12.1 km (7.5 mi),23.3 (2022)
3,Sydney,Australia,Sydney Metro,2019,–,13,36 km (22 mi),16.3 (2022)
4,Vienna,Austria,Vienna U-Bahn,1978,2017,98,83.3 km (51.8 mi),459.8 (2019)
5,Baku,Azerbaijan,Baku Metro,1967,2022,27,40.7 km (25.3 mi),202.5 (2022)
7,Minsk,Belarus,Minsk Metro,1984,2020,33,40.8 km (25.4 mi),225.9 (2022)
8,Brussels,Belgium,Brussels Metro,1976,2009,59,39.9 km (24.8 mi),96.3 (2021)
9,Belo Horizonte,Brazil,Belo Horizonte Metro,1986,2002,19,28.1 km (17.5 mi),54.4 (2019)
10,Brasília,Brazil,Federal District Metro,2001,2020,27,42.38 km (26.33 mi),42.8 (2019)

In [13]:
transit_renamed_df.count()

City                           205
Country region                 205
Name                           205
Service opened                 205
Last expanded                  205
Stations                       205
System length                  205
Annual ridership (millions)    189
dtype: int64

In [ ]:
# TRY to clean up Last expanded and Annual ridership (millions) category. 
transit_renamed_df['Last expanded'] = transit_renamed_df['Last expanded'].replace({'–': 'NA'})
transit_renamed_df.head()

transit_renamed_df['Annual ridership (millions)'] = transit_renamed_df['Annual ridership (millions)'].replace({'n/a': 'Hello'})
transit_renamed_df.head(15)

#potential questions to answer by coding

In [ ]:
#bar plot top 20 longest subway systems by city with color of bar by country   A

In [ ]:
#bar plot top 20 number of passenger subway systems by city with color of bar by country     B

In [ ]:
#bar plot top 20 number subway systems by country with color of bar by country       C

In [ ]:
#bar plot top 20 total subway systems length (in Km or miles) by (either by city and/or total for a country) with color of bar by country    D

In [ ]:
#scatter plot length of subway systems vs number of subway systems     plot C vs D  and linear regression

In [ ]:
#bar plot top 20 number of passenger subway systems by country  with color of bar by country    E

In [ ]:
#scatter plot of number of passenger vs total length of subway - either totals for a city or for a country to indicate how crowded the system is  and linear regression

In [ ]:
#line plot of number of expansions per year (shows increasing demand recently but not surprising)
#line plot of number of new systems per year

In [ ]:
#could look at smallest systems (size or number of stations or riders)
# do we see number of riders per station (choke point crowding)

In [ ]:
# display world map and the cities with subway systems  (using module 6.3 code)